# Generated by Django 5.2.6 on 2025-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
